apiVersion: v1
kind: Service
metadata:
  name: llm-{{ .Values.modelName }}-svc
  namespace: {{ .Values.namespace}}
  labels:
    app.kubernetes.io/name: llm-{{ .Values.modelName }}-svc
    app.kubernetes.io/component: server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: llm-{{ .Values.modelName }}
