apiVersion: v1
kind: Pod
metadata:
  name: llm-sync
  labels:
  namespace: rse

spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node21.cs.aalto.fi
  tolerations:
    - {key: cs-aalto/gpu, value: "true", operator: Equal, effect: NoSchedule}
  restartPolicy: Never

  volumes:
    - name: llm-models
      hostPath:
        path: /srv/dldata/
        type: Directory
    - name: llm-sync-id-rsa
      secret:
        secretName: llm-sync-id-rsa

  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

  containers:
  - name: llm-sync
    image: ghcr.io/aaltoscicomp/git-annex:latest
    command:
    - sh
    - "-x"
    - "-e"
    - "-c"
    - >-
      cp /root/.ssh/id_rsa2 /root/.ssh/id_rsa
      && chmod 600 /root/.ssh/id_rsa
      && cd /models
      && echo BEGIN: $(hostname) $(date)
      && git-annex sync --content
      && git annex find --in . | sed -e 's/^/| /'
      && echo DONE: $(hostname) $(date)
      && sleep 3600
    volumeMounts:
    - name: llm-models
      mountPath: /models
      readOnly: false
    # Making these secrets:
    # kubectl -n rse create secret generic llm-sync-id-rsa --from-file=id_rsa=id_rsa-git-annex-snync --from-file=known_hosts=known_hosts
    - name: llm-sync-id-rsa
      mountPath: /root/.ssh/id_rsa2
      subPath: id_rsa
      readOnly: false
    - name: llm-sync-id-rsa
      mountPath: /root/.ssh/known_hosts
      subPath: known_hosts
