apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm-{{ .Values.modelName }}-{{ .Values.target }}-scaler
  namespace: rse
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-{{ .Values.modelName }}-{{ .Values.target }}
  minReplicas: 1
  maxReplicas: {{ .Values.maxreplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 20
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20
